# Usa la imagen oficial de Node.js
FROM node:18

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia los archivos package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código fuente
COPY . .

# Expone el puerto en el que corre el backend (ajústalo si es necesario)
EXPOSE 3001

# Comando por defecto para ejecutar el backend
CMD ["npm", "start"]
